### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by zHoop** [RealCreepi/Anonyma#1]
https://github.com/RealCreepi/Anonyma/blob/53c2590db4a073db0eba3a1d5a32a9832925bab6/server.js#L1-L8

As you can see above, it uses `var` and i recommend using `const` in this case instead.

**Comment by zHoop** [comment]
https://github.com/RealCreepi/Anonyma/blob/53c2590db4a073db0eba3a1d5a32a9832925bab6/server.js#L26-L28

Prefer `function filterHTML(string)` instead

**Comment by zHoop** [comment]
Everything else looks good for now

**Comment by ad2017gd** [comment]
lol

**Comment by RealCreepi** [comment]
Thank you for helping. Changes have been done or are being worked on.

**Comment by ad2017gd** [comment]
ma pis pe anonyma

**Comment by encezo** [comment]
Censorship,,,, SMH,,,,,,

**Comment by Samyocord** [comment]
:trollface:
